apiVersion: v1
data:
  psql_create_db.sh: "#!/bin/bash\napt-get update && \\\napt-get -y install nano
    && \\\napt-get -y install curl && \\\npsql \"host=${host} port=5432 dbname=vault user=postgres
    sslmode=require target_session_attrs=read-write password=${password}\"  <<
    EOF\n       CREATE TABLE vault_kv_store (\n  parent_path TEXT COLLATE \"C\" NOT
    NULL,\n  path        TEXT COLLATE \"C\",\n  key         TEXT COLLATE \"C\",\n
    \ value       BYTEA,\n  CONSTRAINT pkey PRIMARY KEY (path, key)\n);\nCREATE INDEX
    parent_path_idx ON vault_kv_store (parent_path);\nCREATE TABLE vault_ha_locks
    (\n  ha_key                                      TEXT COLLATE \"C\" NOT NULL,\n
    \ ha_identity                                 TEXT COLLATE \"C\" NOT NULL,\n  ha_value
    \                                   TEXT COLLATE \"C\",\n  valid_until                                 TIMESTAMP
    WITH TIME ZONE NOT NULL,\n  CONSTRAINT ha_key PRIMARY KEY (ha_key)\n);\nEOF"
kind: ConfigMap
metadata:
  name: db-sh
