apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: nginx-ingress-controller
  namespace: flux-system
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./releases/nginx-ingress-controller
  prune: true
  wait: true
  timeout: 2m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: postgres-operator
  namespace: flux-system
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./releases/postgres-operator
  prune: true
  wait: true
  timeout: 2m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: vault
  namespace: flux-system
spec:
  interval: 5m
  # dependsOn:
  #   - name: vault-operator
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./releases/vault
  prune: true
