---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: nginx-ingress-controller
  namespace: nginx-ingress-controller
spec:
  interval: 1m0s
  url: https://charts.bitnami.com/bitnami
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx-ingress-controller
  namespace: nginx-ingress-controller
spec:
  chart:
    spec:
      chart: nginx-ingress-controller
      sourceRef:
        kind: HelmRepository
        name: nginx-ingress-controller
  interval: 1m0s
  releaseName: nginx-ingress-controller
  targetNamespace: nginx-ingress-controller
  values:
    extraArgs:
        enable-ssl-passthrough:
    metrics:
      enabled: true
      serviceMonitor:
        enabled: false
    config:
      use-forwarded-headers: "true"
      compute-full-forwarded-for: "true"
      log-format-escape-json: "true"
      log-format-upstream: '{"ts": "$time_iso8601", 
      "http": {"request_id":"$req_id","method":"$request_method","status_code":$status,"url":"$host$request_uri","host":"$host",
      "uri":"$request_uri","request_time":$request_time,"user_agent":"$http_user_agent","protocol":"$server_protocol",
      "trace_session_id":"$http_trace_session_id","server_protocol":"$server_protocol"},
      "nginx": {"x-forward-for":"$proxy_add_x_forwarded_for","remote_addr":"$proxy_protocol_addr","http_referrer":"$http_referer"}}'
    proxySetHeaders: {
        "Trace-Session-Id": "$http_trace_session_id"
         }
    service:
      type: NodePort
