apiVersion: v1
kind: Namespace
metadata:
  name: vault
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: vault
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: main
  url: https://github.com/hashicorp/vault-helm
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vault
  namespace: vault
spec:
  releaseName: vault
  chart:
    spec:
      sourceRef:
        kind: GitRepository
        namespace: flux-system
        name: vault
      chart: .
  interval: 1m0s
  values:
    global:
      tlsDisable: false
    injector:
      enabled: false
    server:
      extraVolumes:
          - type: secret
            name: vault-certs
      extraEnvironmentVars:
        VAULT_ADDR: https://localhost:8200
        VAULT_CACERT: /vault/userconfig/vault-certs/rootCA.crt
      affinity: null
      standalone:
        enabled: "-"
      ha:
        enabled: true
        config: |
          ui = true
          listener "tcp" {
            address = "[::]:8200"
            cluster_address = "[::]:8201"
            tls_cert_file = "/vault/userconfig/vault-certs/tls.crt"
            tls_key_file = "/vault/userconfig/vault-certs/tls.key"
            tls_ca_cert_file = "/vault/userconfig/vault-certs/rootCA.crt"
          }
          storage "postgresql" {
            connection_url="postgres://postgres:aVbVMJsN4gT4rEg2Z0gDvIEjAjeNQslXcpNTvijSMXtG5YodoVwOAqVlQn1aHGGJ@acid-minimal-cluster:5432/vault?sslmode=require"
            table="vault_kv_store",
            ha_enabled=true,
            ha_table="vault_ha_locks" 
          }
          service_registration "kubernetes" {}
